### ISSUE TITLE
Avoid over-specificity in CSS

### ISSUE THREAD

**Issue by h3xar0n** [cohn17/TeaCozy#3]
The specificity you chose with your CSS selectors gets the job done. One thing to keep in mind is that you may not need to be too specific for a small site. For example, if you had a class, `.section`, inside of `main`, and the only elements with the class were in main, it would be redundant to specify `main`. 

You would only need to specify the parent if it needed to have a different behavior with a different parent. For example, let's say we have a class `.big-button`. Our `header` is black, and our `main` is white. We could say that all of our elements with `.big-button` should be white in the `header`, and `black` in the `main` for good contrast in different contexts, but we want them to be 20px high and 100px wide no matter what:

```css
.big-button {
  height: 20px;
  width: 100px;
}

header {
  background-color: black;
}

header .big-button {
  background-color: white;
}

main {
  background-color: white;
}

main .big-button {
  background-color: black;
}
```

We don't need to specify parentage unless we want a unique behavior for that case. Nevertheless, there are cases in which you need to nest. As a rule of thumb, try to avoid nesting more than 4 levels of parents.

https://github.com/cohn17/TeaCozy/blob/b1c2e16f6e848edf3dc99a86a580e989a609ee9b/resources/css/style.css#L117
